export const INSTITUTIONS: string[] = [
  //ptn
  "Universitas Airlangga",
  "Universitas Andalas",
  "Universitas Bengkulu",
  "Universitas Brawijaya",
  "Universitas Cenderawasih",
  "Universitas Diponegoro",
  "Universitas Gadjah Mada",
  "Universitas Haluoleo",
  "Universitas Hasanuddin",
  "Universitas Indonesia",
  "Universitas Jambi",
  "Universitas Jenderal Soedirman",
  "Universitas Khairun",
  "Universitas Lambung Mangkurat",
  "Universitas Lampung",
  "Universitas Mataram",
  "Universitas Mulawarman",
  "Universitas Negeri Gorontalo",
  "Universitas Nusa Cendana",
  "Universitas Padjadjaran",
  "Universitas Papua",
  "Universitas Pattimura",
  "Universitas Riau",
  "Universitas Sam Ratulangi",
  "Universitas Sebelas Maret",
  "Universitas Sriwijaya",
  "Universitas Sumatera Utara",
  "Universitas Syiah Kuala",
  "Universitas Tadulako",
  "Universitas Tanjungpura",
  "Universitas Udayana",
  //pts
  "Universitas Atmajaya Jakarta",
  "Universitas Hang Tuah",
  "Universitas HKBP Nommensen",
  "Universitas Indonesia Timur",
  "Universitas Islam Indonesia",
  "Universitas Islam Makassar",
  "Universitas Jenderal Achmad Yani",
  "Universitas Krida Wacana",
  "Universitas Kristen Indonesia",
  "Universitas Kristen Maranatha",
  "Universitas Malahayati",
  "Universitas Methodist Indonesia",
  "Universitas Muhammadiyah Jakarta",
  "Universitas Muhammadiyah Makassar",
  "Universitas Muhammadiyah Malang",
  "Universitas Muhammadiyah Palembang",
  "Universitas Muhammadiyah Semarang",
  "Universitas Muhammadiyah Surakarta",
  "Universitas Muhammadiyah Yogyakarta",
  "Universitas Muslim Indonesia",
  "Universitas Pelita Harapan",
  "Universitas Swadaya Gunung Jati",
  "Universitas Tarumanagara",
  "Universitas Trisakti",
  "Universitas Warmadewa",
  "Universitas Wijaya Kusuma Surabaya",
  "YARSI University",
]
